#!/bin/sh
_hostname=$(hostname)
_version=$(cut -d"'" -f2 < /usr/local/lib/python3.9/dist-packages/shikigotchi/_version.py)
echo
echo "(◕‿‿◕) $_hostname"
echo
echo "    Hi! I'm a shikigotchi $_version, please take good care of me!"
echo "    Here are some basic things you need to know to raise me properly!"
echo
echo "    If you want to change my configuration, use /etc/shikigotchi/config.toml"
echo "    All plugin config files are located in /etc/shikigotchi/conf.d/"
echo "    Read the readme if you want to use gdrivesync plugin!!"
echo
echo "    All the configuration options can be found on /etc/shikigotchi/default.toml,"
echo "    but don't change this file because I will recreate it every time I'm restarted!"
echo
echo "    I use oPwnGrid as my main API, you can check stats at https://grid.toshiki.dev"
echo
echo "    I'm managed by systemd. Here are some basic commands."
echo
echo "    If you want to know what I'm doing, you can check my logs with the command"
echo "    - shikilog"
echo "    - sudo shikigotchi --wizard, to help set up a config.toml"
echo "    - sudo shikigotchi --version, to check the current version"
echo "    - sudo shikigotchi --donate, to see how you can donate to this project"
echo "    - sudo shikigotchi --check-update, to see if there is a new version available"
echo
echo "    If you want to know if I'm running, you can use"
echo "    sudo systemctl status shikigotchi"
echo
echo "    You can restart me using"
echo "    shikikill"
echo
echo "    You can learn more about me at https://shikigotchi.toshiki.dev/"